# Generated by Django 3.1 on 2020-12-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'conta', 'verbose_name_plural': 'contas'},
        ),
    ]
