# Generated by Django 3.1.3 on 2021-02-08 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'perfil', 'verbose_name_plural': 'perfis'},
        ),
    ]
