# Generated by Django 3.1.3 on 2021-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210420_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='conf_num',
            field=models.CharField(default='000000000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
