# Generated by Django 3.1.3 on 2021-12-16 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20211216_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='conf_num',
        ),
    ]
