# Generated by Django 3.1.3 on 2021-12-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_account_conf_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
