# Generated by Django 3.1.3 on 2021-12-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20211219_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
