# Generated by Django 3.1.3 on 2022-01-03 19:42

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='telefone'),
        ),
    ]
