# Generated by Django 3.1.3 on 2022-01-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20220103_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notificacoes',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='gênero'),
        ),
    ]
