# Generated by Django 3.1.3 on 2022-01-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20220104_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='subscriber',
            field=models.BooleanField(default=True),
        ),
    ]
