# Generated by Django 3.1.3 on 2021-12-15 12:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to=blog.models.image_wrapper),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('nenhuma', 'Nenhuma'), ('primeiros_passos', 'Primeiros Passos'), ('movimentos', 'Movimentos'), ('treinos', 'Treinos'), ('alimentacao', 'Alimentação'), ('descanso', 'Descanso')], default='nenhuma', max_length=25, verbose_name='Categoria'),
        ),
    ]
