# Generated by Django 3.1.3 on 2021-12-15 13:20

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211215_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default.png', upload_to=blog.models.image_wrapper, verbose_name='Imagem'),
        ),
    ]
